---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: ubuntu-14.04
    driver:
      name: vagrant
  - name: ubuntu-14.04-aws
    driver:
      name: ec2
      aws_ssh_key_id: tpetchel
      security_group_ids: ["sg-49896b2e"]
      image_id: ami-86e0ffe7
      region: us-west-2
      instance_type: t1.micro
      tags:
        "X-Project": "Learn Chef"
    transport:
      ssh_key: ~/.ssh/tpetchel.pem
      username: ubuntu

suites:
  - name: default
    run_list:
      - recipe[learn-the-basics-ubuntu::default]
    attributes:
      workflow:
        packages:
          chef_dk:
            channel: stable
            chefdk_version: 0.11
            chef_client_version: 12.7
