---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2

suites:
  - name: server
    driver:
      customize:
        memory: 2048
      vm_hostname: chef-compliance.local
      network:
        - ["private_network", {ip: "192.168.77.77"}]
    run_list:
      - role[base]
      - recipe[chef_compliance]
    attributes:
